### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by giantfurkii** [Baktus79/BanFromClaim#7]
Can the ability to send the banned person to spawn be added when the claim is banned ? In the latest version, the player in the claim throws the player out of the game in a tight place when he is banned.

**Comment by Baktus79** [comment]
Thank you for your feedback, but I have already arranged a solution for this. Unfortunately, I have not been able to update the wiki page due to health in recent months. 

You can use the command `/bfcsafespot` to set a predefined spot where players get teleported to if there is no ground.

Permission: `bfc.safespot` to use the command. If you have the permission `bfc.admin` it will be included.
Alias:
`/bfcs`
`/bfcsetsafe`
